export const HEX_PRIVKEY_STORAGE_KEY = 'ARC_PRIVATE_KEY'
export const HEX_PUBKEY_STORAGE_KEY = 'ARC_PUBLIC_KEY'
export const API_TOKEN_STORAGE_KEY = 'ARC_API_TOKEN'
export const THEME_STORAGE_KEY = 'ARC_THEME_1'
