export * from 'tamagui'
export * from './MyComponent'
export * from './components/Logo'
export * from './components/Message'
export * from './components/Screen'
export { config } from './tamagui.config'
